AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bookmark-service

  SAM Template for bookmark-service
Globals:
  Function:
    Timeout: 3

Resources:
  SimpleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: simple.handler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Tags:
        Project: bookmark-service

Outputs:
  SimpleFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for simple function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SimpleFunction:
    Description: "Simple Function ARN"
    Value: !GetAtt SimpleFunction.Arn
  SimpleFunctionIamRole:
    Description: "Implicit IAM Role created for a simple function"
    Value: !GetAtt SimpleFunctionRole.Arn
